ssl_certificate /etc/ssl/certs/techhive/fullchain.pem;
ssl_certificate_key /etc/ssl/private/techhive/privkey.pem;
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;

ssl_protocols TLSv1.2 TLSv1.3;
ssl_prefer_server_ciphers off;

add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
